Update katalonkkk.yml

diff --git a/.github/workflows/katalon.yml b/.github/workflows/katalon.yml
--- a/.github/workflows/katalon.yml
+++ b/.github/workflows/katalon.yml
@@ -20,15 +20,22 @@ jobs:
         java-version: '11'
         distribution: 'adopt'
 
-    - name: Download & Extract Katalon Studio Engine 8.6.5 (Linux)
+    - name: Download & Extract Katalon Studio Engine 8.6.5
       run: |
         wget https://download.katalon.com/8.6.5/Katalon_Studio_Engine_Linux_64-8.6.5.tar.gz -O katalon.tar.gz
         tar -xvzf katalon.tar.gz
         chmod -R +x Katalon_Studio_Engine_Linux_64-8.6.5
 
-    - name: List extracted files (debug)
+    - name: Debug File Check
       run: |
-        ls -l ./Katalon_Studio_Engine_Linux_64-8.6.5
+        echo "Current directory:"
+        pwd
+        echo "List root:"
+        ls -l
+        echo "List inside extracted folder:"
+        ls -l Katalon_Studio_Engine_Linux_64-8.6.5
+        echo "Check katalon binary:"
+        file Katalon_Studio_Engine_Linux_64-8.6.5/katalon || echo "File not found"
 
     - name: Run Katalon Tests
       run: |
